replicaCount: 1

image:
  repository: pennlabs/{{ project_name }}
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: true
  domain: example.com

secrets:
  enabled: false
  secretEnv: {{ project_name }}

project_name: {{ project_name }}
