deploy_version: 0.1.8
image_tag: latest

applications:
  - name: django
    image: pennlabs/{{ project_name }}
    secret: {{ project_name }}
    ingress:
      hosts:
        - host: example.com
          paths: ["/"]
    extraEnv:
      - name: DOMAIN
        value: example.com
      - name: DJANGO_SETTINGS_MODULE
        value: {{ project_name }}.settings.production
