replicaCount: 1

image:
  repository: pennlabs/example-django
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80

ingress:
  enabled: true
  domain: example-django.upenn.club

secrets:
  secretEnv: example-django
